# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'github-fetcher' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for github-fetcher
  pod "Alamofire", "~> 5.8.0"
  pod "Kingfisher", "~> 7.8.0"
  pod "SnapKit", "~> 5.6.0"

end
